name: Hardware tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  tests:
    name: Python ${{matrix.python-version}} | ${{matrix.sim}} 
    runs-on: ubuntu-20.04
    env:
      SIM: ${{matrix.sim}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - sim: verilator
            sim-version: v4.106
            python-version: 3.8
    steps:
    - uses: actions/checkout@v1
    - name: Set up Anaconda ${{matrix.python-version}}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{matrix.python-version}}
    - name: Install Conda dependencies
      shell: bash -l {0}
      run: |
        conda info -a
        conda install coloredlogs numba numpy matplotlib pyyaml pytables pytest tqdm scipy
    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        pip install basil-daq>=3.2.0 cocotb==1.5.2 cocotb-bus==0.1.0
    - name: Install Verilator
      if: matrix.sim == 'verilator'
      run: |
        sudo apt install -y --no-install-recommends make g++ perl python3 autoconf flex bison libfl2 libfl-dev zlibc zlib1g zlib1g-dev
        git clone https://github.com/verilator/verilator.git -b ${{matrix.sim-version}}
        cd verilator
        autoconf
        ./configure
        make -j $(nproc)
        sudo make install
    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Test
      shell: bash -l {0}
      run: |
        pytest tjmonopix2/tests/test_*.py
