name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    - development

jobs:
  tests:
    name: Python ${{matrix.python-version}} | ${{matrix.sim}} 
    runs-on: ubuntu-latest
    env:
      SIM: ${{matrix.sim}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - sim: verilator
            sim-version: v5.044
            python-version: '3.13'
    steps:
    - uses: actions/checkout@v6
    - name: Set up python
      uses: actions/setup-python@v6
      with:
        python-version: ${{matrix.python-version}}
        cache: 'pip'
    - name: Install Dependencies
      run:  pip install "cocotb>=2.0" "cocotb-bus" coloredlogs numba numpy matplotlib pyyaml tables pytest tqdm scipy
    - name: Install basil from repo
      run: git clone -b master --depth 1 https://github.com/SiLab-Bonn/basil.git; cd basil; pip install .; cd ..;
    - name: Install Verilator
      if: matrix.sim == 'verilator'
      run: |
        sudo apt install -y --no-install-recommends make g++ help2man perl python3 autoconf flex bison libfl2 libfl-dev zlib1g zlib1g-dev
        git clone https://github.com/verilator/verilator.git -b ${{matrix.sim-version}}
        cd verilator
        autoconf
        ./configure
        make -j $(nproc)
        sudo make install
    - name: Install package
      run: pip install .
    - name: Test
      run: pytest tjmonopix2/tests/
